### ISSUE TITLE
I found a funny typo in the README file =))

### ISSUE THREAD

**Issue by Serena1432** [ndbiaw/VietNameseToT33nC0d3#1]
I have just found a typo in the `Deploy to Heroku` button that leads to the following URL:
`https://heroku.com/deploy?template=https://heroku.com/deploy?template=https://github.com/ndbiaw/VietNameseToT33nC0d3`

There's 2 `https://heroku.com/deploy?template=` in the URL which causes an invalid template URL. Please fix it.

**Comment by nayumiDEV** [comment]
thanks OwO

**Comment by nayumiDEV** [comment]
Fixed
